In [1]:
import shared as ip2

In [2]:
inp = ip2.readCsvNamedMatrix(open('testdata/input.csv'))

In [3]:
inp

In [4]:
inp.data

array([[ 0.10753 ,  0.66153 ,  0.11155 ,  0.95427 ,  0.99463 ,  0.73567 ,
         0.88821 ,  0.93455 ,  1.3959  ,  0.98777 , -0.12094 ,  0.45794 ,
        -0.2888  , -0.69278 , -0.72308 , -1.0159  , -1.022   , -0.63293 ,
        -0.50002 , -0.27988 , -0.16046 , -0.2415  ,  0.14345 ,  0.6208  ,
         0.6611  ,  0.98877 ,  1.0763  ,  0.93652 ,  1.0337  ,  0.70857 ,
         0.85785 ,  0.20447 , -0.064732, -0.31094 , -1.0227  , -0.3925  ,
        -0.80099 , -1.1259  , -0.72314 , -1.2732  , -0.80228 , -0.61161 ,
        -0.23091 ,  0.062572, -0.17298 ,  0.28874 ,  0.53034 ,  0.90737 ,
         1.1495  ,  1.2191  ,  0.8022  ,  0.8815  ,  0.43735 ,  0.21118 ,
         0.14767 ,  0.15748 , -0.58782 , -0.6059  , -0.91114 , -0.75146 ,
        -1.215   , -0.92436 , -0.67133 , -0.3432  ,  0.014087,  0.017186,
        -0.29832 ,  0.14629 ,  0.351   ,  1.2519  ,  0.80775 ,  1.1468  ,
         0.93644 ,  1.0437  ,  0.5272  ,  0.15343 , -0.13543 , -0.051403,
        -0.46936 , -0.71938 , -0.58216

In [5]:
inp.nrows()

2

In [6]:
import numpy as np

In [8]:
np.mean(inp.data,axis=1)

array([ 0.03573463, -0.03382306])

In [17]:
import scipy.stats as sps

In [19]:
kek = sps.mstats.zscore(inp.data,axis=1,ddof=1)

In [22]:
np.std(kek,axis=1,ddof=1)

array([ 1.,  1.])